spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_pruebas
spring.datasource.username=postgres
spring.datasource.password=password123

# Calidad: Esto crea las tablas automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Usuario de prueba para desarrollo
spring.security.user.name=admin
spring.security.user.password=admin123

server.port=8081

# ✅ Habilita escaneo de controladores MVC (@Controller)
springdoc.show-mvc-mappings=true
springdoc.default-produces-media-type=application/json