spring.application.name=jmeter-app-ejemplo
server.port=8080
server.servlet.context-path=/

# Logging
logging.level.root=WARN
logging.level.com.calidad.jmeter=INFO

# Actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
