# -*- coding: utf-8 -*-
"""Punto_5_20260303.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1volLjRN8C7JEcPGica7t2zma2b60eilg
"""

# Este programa implementa una Red Neuronal Artificial llamada MLP (Multi-Layer Perceptron).
# El objetivo es aprender el problema l車gico XOR, que no puede resolverse con un perceptr車n simple.
# El programa:
# 1. Define funciones de activaci車n (sigmoid) y su derivada.
# 2. Crea una clase MLP con propagaci車n hacia adelante (forward) y hacia atr芍s (backpropagation).
# 3. Entrena la red neuronal con el dataset XOR.
# 4. Muestra las predicciones del modelo.
# 5. Grafica:
#    - La evoluci車n del error durante el entrenamiento
#    - La frontera de decisi車n
#    - Comparaci車n entre valores reales y predichos.

import numpy as np  # Importa NumPy para operaciones matem芍ticas y manejo de matrices
import matplotlib.pyplot as plt  # Importa Matplotlib para crear gr芍ficos

np.random.seed(42)  # Fija la semilla aleatoria para que los resultados sean reproducibles


def sigmoid(z):  # Define la funci車n de activaci車n sigmoide
    return 1 / (1 + np.exp(-z))  # Aplica la f車rmula de la sigmoide


def sigmoid_derivative(a):  # Define la derivada de la funci車n sigmoide
    return a * (1 - a)  # F車rmula de la derivada usando la salida de la sigmoide


class MLP:  # Define la clase de la red neuronal Multilayer Perceptron

    def __init__(self, layers, learning_rate=0.1, epochs=10000):
        # Constructor de la red neuronal

        self.layers = layers  # Lista que indica el n迆mero de neuronas por capa
        self.learning_rate = learning_rate  # Tasa de aprendizaje
        self.epochs = epochs  # N迆mero de 谷pocas de entrenamiento

        self.weights = []  # Lista para guardar matrices de pesos
        self.biases = []  # Lista para guardar los bias de cada capa
        self.loss_history = []   # Lista para guardar la evoluci車n del error

        # Inicializaci車n din芍mica de pesos y bias
        for i in range(len(layers)-1):  # Recorre cada par de capas
            self.weights.append(np.random.randn(layers[i], layers[i+1]))
            # Crea una matriz de pesos aleatoria entre la capa actual y la siguiente

            self.biases.append(np.zeros((1, layers[i+1])))
            # Inicializa los bias en cero


    def forward(self, X):  # Propagaci車n hacia adelante (forward propagation)

        self.activations = [X]  # Guarda la activaci車n de la capa de entrada

        for i in range(len(self.weights)):  # Recorre todas las capas
            z = np.dot(self.activations[-1], self.weights[i]) + self.biases[i]
            # Calcula la combinaci車n lineal (entrada * pesos + bias)

            a = sigmoid(z)  # Aplica funci車n de activaci車n
            self.activations.append(a)  # Guarda la activaci車n de esta capa

        return self.activations[-1]  # Devuelve la salida final de la red


    def backward(self, X, y):  # Retropropagaci車n del error (Backpropagation)

        m = X.shape[0]  # N迆mero de muestras
        deltas = []  # Lista para guardar los gradientes de error

        # Error en la capa de salida
        error = self.activations[-1] - y  # Diferencia entre predicci車n y valor real

        delta = error * sigmoid_derivative(self.activations[-1])
        # Gradiente del error multiplicado por derivada de la sigmoide

        deltas.append(delta)  # Guarda el delta de la capa de salida

        # Propagaci車n del error hacia atr芍s
        for i in reversed(range(len(self.weights)-1)):  # Recorre capas en orden inverso
            error = np.dot(deltas[-1], self.weights[i+1].T)
            # Propaga el error hacia la capa anterior

            delta = error * sigmoid_derivative(self.activations[i+1])
            # Calcula el nuevo delta

            deltas.append(delta)  # Guarda el delta

        deltas.reverse()  # Invierte el orden para coincidir con las capas

        # Actualizaci車n de pesos y bias
        for i in range(len(self.weights)):  # Recorre cada capa
            self.weights[i] -= self.learning_rate * np.dot(self.activations[i].T, deltas[i]) / m
            # Ajusta los pesos usando gradiente descendente

            self.biases[i] -= self.learning_rate * np.sum(deltas[i], axis=0, keepdims=True) / m
            # Ajusta los bias


    def fit(self, X, y):  # Funci車n para entrenar la red

        for epoch in range(self.epochs):  # Recorre todas las 谷pocas
            output = self.forward(X)  # Realiza propagaci車n hacia adelante
            self.backward(X, y)  # Ajusta los pesos con backpropagation

            loss = np.mean((y - output) ** 2)  # Calcula el error cuadr芍tico medio (MSE)
            self.loss_history.append(loss)  # Guarda el error en el historial

            if epoch % 1000 == 0:  # Cada 1000 谷pocas
                print(f"Epoch {epoch}, Loss: {loss}")  # Imprime el error


    def predict(self, X):  # Funci車n para realizar predicciones
        output = self.forward(X)  # Calcula la salida de la red
        return np.round(output)  # Redondea a 0 o 1


# -------------------------
# DATOS XOR
# -------------------------

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])  # Entradas posibles del problema XOR

y = np.array([[0],
              [1],
              [1],
              [0]])  # Salidas del problema XOR


modelo = MLP(
    layers=[2, 8, 1],  # 2 neuronas entrada, 8 ocultas, 1 salida
    learning_rate=0.1,  # Tasa de aprendizaje
    epochs=10000  # N迆mero de 谷pocas
)

modelo.fit(X, y)  # Entrena el modelo con los datos XOR

print("Predicciones XOR:")  # Muestra texto en consola
print(modelo.predict(X))  # Imprime predicciones del modelo


# ===============================
# 1. GR芍FICA DE ERROR
# ===============================

plt.figure()  # Crea una nueva figura
plt.plot(modelo.loss_history)  # Grafica la evoluci車n del error
plt.title("Evoluci車n del Error (Loss)")  # T赤tulo del gr芍fico
plt.xlabel("谷pocas")  # Etiqueta eje X
plt.ylabel("MSE")  # Etiqueta eje Y
plt.show()  # Muestra la gr芍fica


# ===============================
# 2. FRONTERA DE DECISI車N
# ===============================

x_min, x_max = -0.5, 1.5  # L赤mites del eje X
y_min, y_max = -0.5, 1.5  # L赤mites del eje Y

xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                     np.linspace(y_min, y_max, 200))
# Crea una malla de puntos para evaluar el modelo

grid = np.c_[xx.ravel(), yy.ravel()]  # Convierte la malla en lista de puntos

Z = modelo.predict(grid)  # Predice la clase para cada punto

Z = Z.reshape(xx.shape)  # Reorganiza las predicciones a la forma de la malla

plt.figure()  # Nueva figura
plt.contourf(xx, yy, Z, alpha=0.3)  # Dibuja regiones de decisi車n
plt.scatter(X[:,0], X[:,1], c=y.flatten())  # Grafica los puntos del dataset
plt.title("Frontera de Decisi車n - XOR")  # T赤tulo
plt.xlabel("X1")  # Etiqueta eje X
plt.ylabel("X2")  # Etiqueta eje Y
plt.show()  # Muestra la gr芍fica


# ===============================
# 3. REAL VS PREDICHO
# ===============================

predicciones = modelo.forward(X)  # Calcula las predicciones reales (sin redondear)

plt.figure()  # Nueva figura
plt.plot(predicciones, 'o', label="Predicho")  # Grafica predicciones
plt.plot(y, 'x', label="Real")  # Grafica valores reales
plt.legend()  # Muestra la leyenda
plt.title("Valores Reales vs Predichos")  # T赤tulo
plt.show()  # Muestra la gr芍fica