# -*- coding: utf-8 -*-
"""Punto_4_20260303.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pn5OkyQCL2GMO5rDrlWR4lSw66Cv1TeX
"""

# Este programa implementa un modelo de aprendizaje automático llamado Perceptrón.
# El perceptrón se usa para clasificación binaria (0 o 1). El código:
# 1. Define la clase Perceptron.
# 2. Genera dos conjuntos de datos (uno con la compuerta lógica AND y otro con datos gaussianos separables).
# 3. Entrena el perceptrón con esos datos.
# 4. Calcula la exactitud del modelo.
# 5. Grafica la frontera de decisión y los errores por época.
# 6. Guarda datasets y gráficos en archivos.

import numpy as np  # Importa la librería NumPy para cálculos numéricos y manejo de arreglos
import pandas as pd  # Importa Pandas para manejar datos en forma de tablas (DataFrame)
import matplotlib.pyplot as plt  # Importa Matplotlib para crear gráficos

class Perceptron:  # Define la clase Perceptron (modelo de clasificación lineal)

    def __init__(self, learning_rate: float = 0.1, epochs: int = 100, shuffle: bool = True):  
        # Constructor de la clase. Se ejecuta al crear un objeto Perceptron.
        self.learning_rate = learning_rate  # Tasa de aprendizaje (qué tan grandes son los ajustes de los pesos)
        self.epochs = epochs  # Número máximo de veces que el modelo recorrerá todo el dataset
        self.shuffle = shuffle  # Indica si los datos se mezclan en cada época
        self.weights = None  # Vector de pesos del modelo (inicialmente vacío)
        self.bias = None  # Sesgo (bias) del modelo
        self.errors_history_ = []  # Lista para guardar cuántos errores hubo en cada época
        self.epochs_run_ = 0  # Guarda cuántas épocas realmente se ejecutaron

    def activation(self, z):  # Función de activación del perceptrón
        return 1 if z >= 0 else 0  # Si el valor es >=0 devuelve 1, si no devuelve 0

    def fit(self, X: np.ndarray, y: np.ndarray):  # Método para entrenar el modelo
        n_samples, n_features = X.shape  # Obtiene número de muestras y número de características

        self.weights = np.random.uniform(-0.01, 0.01, size=n_features)  
        # Inicializa los pesos con valores aleatorios pequeños

        self.bias = float(np.random.uniform(-0.01, 0.01))  
        # Inicializa el sesgo con un valor aleatorio pequeño

        self.errors_history_.clear()  # Limpia el historial de errores si existía uno anterior

        for epoch in range(1, self.epochs + 1):  # Recorre las épocas de entrenamiento
            idx = np.random.permutation(n_samples) if self.shuffle else np.arange(n_samples)  
            # Mezcla los índices de los datos si shuffle=True

            errors = 0  # Contador de errores en esta época

            for i in idx:  # Recorre cada muestra del dataset
                xi = X[i]  # Selecciona la muestra actual
                zi = float(np.dot(xi, self.weights) + self.bias)  
                # Calcula la combinación lineal (producto punto + bias)

                y_hat = self.activation(zi)  # Predicción del perceptrón usando la función de activación
                error = y[i] - y_hat  # Calcula el error entre la etiqueta real y la predicción

                if error != 0:  # Si hubo error
                    self.weights = self.weights + self.learning_rate * error * xi  
                    # Ajusta los pesos

                    self.bias = self.bias + self.learning_rate * error  
                    # Ajusta el sesgo

                    errors += 1  # Aumenta el contador de errores

            self.errors_history_.append(errors)  # Guarda el número de errores de esta época

            if errors == 0:  # Si no hubo errores
                self.epochs_run_ = epoch  # Guarda la época en que convergió
                break  # Termina el entrenamiento anticipadamente

        else:  # Si nunca llegó a cero errores
            self.epochs_run_ = self.epochs  # Se ejecutaron todas las épocas

        return self  # Devuelve el modelo entrenado

    def predict(self, X: np.ndarray) -> np.ndarray:  # Método para hacer predicciones
        z = X @ self.weights + self.bias  # Calcula la combinación lineal
        return (z >= 0).astype(int)  # Devuelve 1 o 0 según el resultado

    def score(self, X: np.ndarray, y: np.ndarray) -> float:  # Método para calcular exactitud
        return (self.predict(X) == y).mean()  # Calcula el porcentaje de predicciones correctas


def save_and_load_csv(df: pd.DataFrame, path: str) -> pd.DataFrame:  
    # Función que guarda un DataFrame en CSV y luego lo vuelve a cargar
    df.to_csv(path, index=False)  # Guarda el DataFrame en un archivo CSV
    return pd.read_csv(path)  # Lee el CSV y lo devuelve como DataFrame


def make_and_dataset_csv(path: str) -> pd.DataFrame:  
    # Genera un dataset de la compuerta lógica AND

    X = np.array([[0,0], [0,1], [1,0], [1,1]], dtype=float)  
    # Entradas posibles de la compuerta AND

    y = np.array([0, 0, 0, 1], dtype=int)  
    # Salidas correspondientes de la compuerta AND

    df = pd.DataFrame({'x1': X[:,0], 'x2': X[:,1], 'y': y})  
    # Crea un DataFrame con las variables x1, x2 y la etiqueta y

    return save_and_load_csv(df, path)  
    # Guarda y vuelve a cargar el dataset


def make_gaussians_separable_csv(path: str, n_per_class: int = 120, seed: int = 0) -> pd.DataFrame:
    # Genera un dataset con dos clases separables usando distribuciones gaussianas

    rng = np.random.default_rng(seed)  # Crea un generador de números aleatorios con semilla

    mean0 = np.array([-2.0, -2.0])  # Media de la clase 0
    mean1 = np.array([ 2.0,  2.0])  # Media de la clase 1

    cov = np.array([[0.7, 0.15],[0.15, 0.7]])  # Matriz de covarianza

    X0 = rng.multivariate_normal(mean0, cov, size=n_per_class)  
    # Genera datos para la clase 0

    X1 = rng.multivariate_normal(mean1, cov, size=n_per_class)  
    # Genera datos para la clase 1

    y0 = np.zeros(n_per_class, dtype=int)  # Etiquetas clase 0
    y1 = np.ones(n_per_class, dtype=int)  # Etiquetas clase 1

    X = np.vstack([X0, X1])  # Une las muestras de ambas clases
    y = np.concatenate([y0, y1])  # Une las etiquetas

    df = pd.DataFrame({'x1': X[:,0], 'x2': X[:,1], 'y': y})  
    # Crea DataFrame

    return save_and_load_csv(df, path)  # Guarda y carga el dataset


def plot_decision_boundary(X: np.ndarray, y: np.ndarray, model: Perceptron, title: str, filename: str):
    # Función para graficar la frontera de decisión del perceptrón

    import matplotlib.pyplot as plt  # Importa matplotlib

    plt.figure(figsize=(6,5))  # Crea una figura

    plt.scatter(X[y==0,0], X[y==0,1], c='tab:blue', label='Clase 0', s=25)  
    # Grafica los puntos de la clase 0

    plt.scatter(X[y==1,0], X[y==1,1], c='tab:orange', label='Clase 1', s=25)  
    # Grafica los puntos de la clase 1

    w, b = model.weights, model.bias  # Obtiene pesos y bias del modelo

    if abs(w[1]) > 1e-10:  # Si el peso de x2 no es cero
        x_vals = np.linspace(X[:,0].min()-0.5, X[:,0].max()+0.5, 200)  
        # Crea valores de x para la línea

        y_vals = -(w[0]*x_vals + b)/w[1]  
        # Calcula los valores de y de la frontera

        plt.plot(x_vals, y_vals, 'k--', lw=2, label='Frontera de decisión')  
        # Dibuja la línea

    else:  # Si la frontera es vertical
        x_const = -b/(w[0] + 1e-12)  
        plt.axvline(x_const, color='k', linestyle='--', lw=2, label='Frontera de decisión')

    plt.title(title)  # Título del gráfico
    plt.xlabel('x1')  # Nombre del eje X
    plt.ylabel('x2')  # Nombre del eje Y
    plt.grid(alpha=0.3)  # Activa la cuadrícula
    plt.legend()  # Muestra la leyenda
    plt.tight_layout()  # Ajusta el diseño
    plt.savefig(filename, dpi=150)  # Guarda la imagen
    plt.close()  # Cierra la figura


def plot_errors(model: Perceptron, title: str, filename: str):
    # Función para graficar los errores por época

    import matplotlib.pyplot as plt

    plt.figure(figsize=(6,4))  # Crea la figura

    plt.plot(range(1, len(model.errors_history_)+1), model.errors_history_, marker='o')  
    # Grafica los errores por cada época

    plt.title(title)  # Título
    plt.xlabel('Época')  # Eje X
    plt.ylabel('Errores (actualizaciones)')  # Eje Y

    plt.grid(alpha=0.3)  # Cuadrícula
    plt.tight_layout()  # Ajusta diseño
    plt.savefig(filename, dpi=150)  # Guarda gráfico
    plt.close()  # Cierra figura


# ===== ENTRENAMIENTO CON DATASET AND =====

and_df = make_and_dataset_csv('and_dataset.csv')  # Genera y guarda el dataset AND

X_and = and_df[['x1','x2']].to_numpy(float)  # Convierte columnas x1,x2 en matriz NumPy
y_and = and_df['y'].to_numpy(int)  # Convierte columna y en vector NumPy

per_and = Perceptron(learning_rate=0.2, epochs=100)  # Crea modelo perceptrón

per_and.fit(X_and, y_and)  # Entrena el modelo

acc_and = per_and.score(X_and, y_and)  # Calcula exactitud

plot_decision_boundary(X_and, y_and, per_and,
                       f'AND: frontera (acc={acc_and:.2f}, épocas={per_and.epochs_run_})',
                       'and_boundary.png')  # Grafica frontera

plot_errors(per_and, 'AND: errores por época', 'and_errors.png')  # Grafica errores


# ===== ENTRENAMIENTO CON DATASET GAUSSIANO =====

gauss_df = make_gaussians_separable_csv('gauss_dataset.csv', n_per_class=120, seed=3)  
# Genera dataset separable gaussiano

X_g = gauss_df[['x1','x2']].to_numpy(float)  # Extrae variables
y_g = gauss_df['y'].to_numpy(int)  # Extrae etiquetas

per_g = Perceptron(learning_rate=0.05, epochs=100)  # Crea perceptrón

per_g.fit(X_g, y_g)  # Entrena modelo

acc_g = per_g.score(X_g, y_g)  # Calcula exactitud

plot_decision_boundary(X_g, y_g, per_g,
                       f'Gauss separable: frontera (acc={acc_g:.2f}, épocas={per_g.epochs_run_})',
                       'gauss_boundary.png')  # Grafica frontera

plot_errors(per_g, 'Gauss separable: errores por época', 'gauss_errors.png')  # Grafica errores


# ===== REPORTE FINAL =====

print('=== REPORTE ===')  # Imprime encabezado
print('--- AND ---')  # Sección AND

print('Pesos:', per_and.weights)  # Muestra pesos aprendidos
print('Sesgo:', round(per_and.bias, 4))  # Muestra bias
print('Épocas usadas:', per_and.epochs_run_)  # Número de épocas usadas
print('Exactitud:', round(acc_and, 3))  # Exactitud del modelo
print('Archivos: and_dataset.csv, and_boundary.png, and_errors.png')  # Archivos generados

print('')

print('--- GAUSS ---')  # Sección Gauss
print('Pesos:', per_g.weights)  # Pesos
print('Sesgo:', round(per_g.bias, 4))  # Bias
print('Épocas usadas:', per_g.epochs_run_)  # Épocas usadas
print('Exactitud:', round(acc_g, 3))  # Exactitud
print('Archivos: gauss_dataset.csv, gauss_boundary.png, gauss_errors.png')  # Archivos generados