name: CI Autospark

on:
  push:
    branches:
      - grupo2
  pull_request:
    branches:
      - grupo2

jobs:
  backend-tests:
    name: Pruebas unitarias backend
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Ejecutar pruebas backend
        working-directory: app
        run: mvn clean test